services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      cd server && uv sync --frozen
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
