"""change to not nullable for fk in templates

Revision ID: b02f67f087ba
Revises: 222f54f52c6f
Create Date: 2025-09-17 00:34:20.846789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b02f67f087ba'
down_revision: Union[str, Sequence[str], None] = '222f54f52c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.alter_column('templates', 'pdf_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('templates', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('templates', 'pdf_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
